openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate OpenAPI v3 specification
  version: 1.0.0
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://api.example.com/v1
    description: Main (production) server
paths:
  /items:
    get:
      summary: List all items
      operationId: listItems
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
      tags: ListItems
  "/items/{itemId}":
    get:
      summary: Get an item by ID
      operationId: getItemById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An item object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
      tags: GetItemById
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
