name: Generate SDK

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'SDK Name'
        type: string
        default: rapid
      version:
        description: 'SDK Version. (0.0.x-SNAPSHOT)'
        type: number
        required: true
      templates:
        description: 'Custom templates path to merge with base templates'
        type: choice
        options:
          - 'dummy/templates'
          - ''
        default: ''

jobs:
  #  upload-artifacts:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout current repository
  #        uses: actions/checkout@v4
  #        with:
  #          repository: ''
  #          ref: ''
  #
  #      - name: Upload specs
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: specs
  #          path: specs.yaml
  #
  #      - name: Checkout main SDK repository
  #        uses: actions/checkout@v4
  #        with:
  #          repository: 'ExpediaGroup/expediagroup-java-sdk'
  #          path: sdk-repo
  #
  #      - name: Confirm templates exist
  #        run: |
  #          ls sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk
  #
  #      - name: Upload templates
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: templates
  #          path: sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk
  #
  #  transform-specs:
  #    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-transform-specs.yaml@main
  #    needs: [upload-artifacts]
  #    with:
  #      transformations: '--headers --operationIdsToTags'

  #  confirm-upload:
  #    runs-on: ubuntu-latest
  #    needs: [transform-specs]
  #    steps:
  #      - name: Download specs
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: specs
  #          path: .
  #
  #      - name: Download specs
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: tspecs
  #          path: .
  #
  #      - name: Download templates
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: templates
  #          path: sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk
  #
  #      - name: List specs
  #        run: |
  #          ls specs.yaml
  #          ls tspecs.yaml
  #
  #      - name: List templates
  #        run: ls ./sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk

  #  generate-sdk:
  #    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-generate.yaml@mohnoor94/SDK-1232
  ##    needs: [confirm-upload]
  #    needs: [transform-specs]
  #    with:
  #      name: rapid
  #      version: 0.0.6-SNAPSHOT
  #      templates: sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk

  #  publish-sources:
  #    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-publish-sources.yaml@main
  #    needs: [generate-sdk]
  #    with:
  #      version: 0.0.6-SNAPSHOT
  #      path: code

  #  publish:
  #    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-release.yaml@mohnoor94/SDK-1232
  #    needs: [generate-sdk]
  #

  generate-and-publish:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@mohnoor94/SDK-1394
    with:
      name: ${{ inputs.name }}
      version: 0.0.${{ inputs.version }}-SNAPSHOT
      custom_templates_path: ${{ inputs.templates }}
