name: Generate SDK

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Upload specs
        uses: actions/upload-artifact@v4
        with:
          name: specs
          path: specs.yaml

      - name: Checkout main SDK repository
        uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/expediagroup-java-sdk'
          path: sdk-repo

      - name: Upload templates
        uses: actions/upload-artifact@v4
        with:
          name: templates
          path: sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk

  transform-specs:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfeserve-transform-specs.yaml@mohnoor94/add-spec-transformation-selfserve-action
    needs: [ upload-artifacts ]
    with:
      transformers: '--headers --operationIdsToTags --endpoint /'

  confirm-upload:
    runs-on: ubuntu-latest
    needs: [ transform-specs ]
    steps:
      - name: Download specs
        uses: actions/download-artifact@v4
        with:
          name: specs
          path: .

      - name: Download specs
        uses: actions/download-artifact@v4
        with:
          name: tspecs
          path: .

      - name: Download templates
        uses: actions/download-artifact@v4
        with:
          name: templates
          path: .

      - name: List specs
        run: |
          ls specs.yaml
          ls tspecs.yaml

      - name: List templates
        run: ls sdk-repo/generator/openapi/src/main/resources/templates/expediagroup-sdk

  generate-sdk:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-generate.yaml@main
    needs: [ confirm-upload ]
    with:
      name: rapid
      version: 0.0.1
      templates: templates
      specs_key: tspecs