name: Generate SDK

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'SDK Name'
        type: string
        default: rapid
      version:
        description: 'SDK Version (0.0.x-SNAPSHOT)'
        type: number
        required: true
      templates:
        description: 'Custom templates path to merge with base templates'
        type: choice
        options:
          - 'dummy/templates'
          - ''
        default: ''

jobs:
  generate-and-publish:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@mohnoor94/SDK-1394
    with:
      name: ${{ inputs.name }}
      version: 0.0.${{ inputs.version }}-SNAPSHOT
      custom_templates_path: ${{ inputs.templates }}
