name: Auto First Approval for Bot PRs
on: pull_request

jobs:
  auto-first-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' || github.actor == 'mohnoor94'
    steps:
      - name: Provide first approval
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Automatic first approval for bot PR. Still requires human review."
