name: Contribution Quality Checks
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - auto_merge_enabled
jobs:
  contribution-lint:
    name: Contribution Details Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Pull Request Title Validation
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: npx commitlint --verbose <<< "$PR_TITLE"