name: Resolve Templates

on:
  workflow_dispatch:
    inputs:
      base_templates:
        description: 'Base SDK templates path (without the versioned directories)'
        type: string
        default: 'dummy/base'
      custom_templates:
        description: 'Custom templates path to merge with base templates'
        type: string
        default: 'dummy/folder2'
      combined_templates_key:
        description: 'Key to the combined templates artifact'
        type: string
        default: 'templates'

jobs:
  combine-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Combine templates
        run: |
          cp -r ${{ inputs.base_templates }} tmp/${{ inputs.combined_templates_key }}

          if [ -d ${{ inputs.custom_templates }} ]; then
              cp -r ${{ inputs.custom_templates }}/* tmp/${{ inputs.combined_templates_key }}
          fi

      - name: Upload combined templates
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.combined_templates_key }}
          path: ${{ inputs.combined_templates_key }}